import { sql } from "drizzle-orm";
import {
  check,
  AnyPgColumn,
  index,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  integer,
} from "drizzle-orm/pg-core";
import { user } from "./auth";
import { oauthClients } from "./oauth-clients";
import { timestamps } from "./helpers";

export const deviceClients = pgTable(
  "device_clients",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    ownerUserId: text("owner_user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    oauthClientId: uuid("oauth_client_id")
      .notNull()
      .references(() => oauthClients.id, { onDelete: "restrict" }),
    /** Stable random installation id generated by the TV app. */
    installationId: varchar("installation_id", { length: 64 }),
    displayName: varchar("display_name", { length: 64 }).notNull(),
    deviceType: varchar("device_type", { length: 32 }).notNull(),
    platform: varchar("platform", { length: 32 }).notNull(),
    platformVersion: varchar("platform_version", { length: 64 }).notNull(),
    appVersion: varchar("app_version", { length: 64 }).notNull(),
    identitySummary: varchar("identity_summary", { length: 120 }).notNull(),
    status: varchar("status", { length: 16 }).notNull().default("active"),
    registeredAt: timestamp("registered_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by").references(() => user.id, {
      onDelete: "restrict",
    }),
    version: integer("version").notNull().default(1),
    ...timestamps,
  },
  (t) => [
    index("device_clients_owner_status_heartbeat_idx").on(
      t.ownerUserId,
      t.status,
      t.lastHeartbeatAt,
      t.id,
    ),
    index("device_clients_oauth_client_idx").on(t.oauthClientId),
    uniqueIndex("device_clients_oauth_installation_idx").on(
      t.oauthClientId,
      t.installationId,
    ),
    check(
      "device_clients_status_check",
      sql`(${t.status} = 'active' AND ${t.revokedAt} IS NULL AND ${t.revokedBy} IS NULL)
        OR (${t.status} = 'revoked' AND ${t.revokedAt} IS NOT NULL AND ${t.revokedBy} IS NOT NULL)`,
    ),
  ],
);

export const deviceAuthorizationGrants = pgTable(
  "device_authorization_grants",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    oauthClientId: uuid("oauth_client_id")
      .notNull()
      .references(() => oauthClients.id, { onDelete: "cascade" }),
    deviceCodeHash: varchar("device_code_hash", { length: 64 }).notNull(),
    userCodeDigest: varchar("user_code_digest", { length: 64 }).notNull(),
    deviceType: varchar("device_type", { length: 32 }).notNull(),
    platform: varchar("platform", { length: 32 }).notNull(),
    platformVersion: varchar("platform_version", { length: 64 }).notNull(),
    appVersion: varchar("app_version", { length: 64 }).notNull(),
    identitySummary: varchar("identity_summary", { length: 120 }).notNull(),
    requestedDisplayName: varchar("requested_display_name", { length: 64 }),
    status: varchar("status", { length: 16 }).notNull().default("pending"),
    ownerUserId: text("owner_user_id").references(() => user.id, {
      onDelete: "cascade",
    }),
    approvedDisplayName: varchar("approved_display_name", { length: 64 }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    pollIntervalSeconds: integer("poll_interval_seconds").notNull().default(5),
    lastPolledAt: timestamp("last_polled_at", { withTimezone: true }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    deviceClientId: uuid("device_client_id").references(
      () => deviceClients.id,
      { onDelete: "set null" },
    ),
    version: integer("version").notNull().default(1),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("device_authorization_grants_device_code_idx").on(
      t.deviceCodeHash,
    ),
    uniqueIndex("device_authorization_grants_user_code_idx").on(
      t.userCodeDigest,
    ),
    index("device_authorization_grants_status_expiry_idx").on(
      t.status,
      t.expiresAt,
    ),
    uniqueIndex("device_authorization_grants_device_client_idx").on(
      t.deviceClientId,
    ),
    check(
      "device_authorization_grants_status_check",
      sql`${t.status} IN ('pending', 'approved', 'denied', 'consumed', 'expired')`,
    ),
  ],
);

export const deviceRefreshTokens = pgTable(
  "device_refresh_tokens",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    deviceClientId: uuid("device_client_id")
      .notNull()
      .references(() => deviceClients.id, { onDelete: "cascade" }),
    oauthClientId: uuid("oauth_client_id")
      .notNull()
      .references(() => oauthClients.id, { onDelete: "cascade" }),
    familyId: uuid("family_id").notNull(),
    generation: integer("generation").notNull(),
    tokenHash: varchar("token_hash", { length: 64 }).notNull(),
    tokenPrefix: varchar("token_prefix", { length: 12 }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    replacedById: uuid("replaced_by_id").references(
      (): AnyPgColumn => deviceRefreshTokens.id,
      { onDelete: "set null" },
    ),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("device_refresh_tokens_family_generation_idx").on(
      t.familyId,
      t.generation,
    ),
    uniqueIndex("device_refresh_tokens_hash_idx").on(t.tokenHash),
    index("device_refresh_tokens_device_expiry_idx").on(
      t.deviceClientId,
      t.revokedAt,
      t.expiresAt,
    ),
    check(
      "device_refresh_tokens_generation_check",
      sql`${t.generation} > 0`,
    ),
  ],
);
