export {
  syncLogs,
  m3uSources,
  xmltvSources,
  channels,
  rawM3uChannels,
  rawXmltvChannels,
  programmes,
  canonicalChannels,
  canonicalEpgBindings,
  channelOverrides,
  channelStreams,
  // Safe Operations (T015–T018)
  sourceImportSnapshots,
  sourceImportSnapshotItems,
  operationChangeSets,
  operationChangeItems,
  operationLeases,
  recoveryPoints,
  recoveryPointItems,
  auditEvents,
  outboxEvents,
  idempotencyRecords,
  canonicalChannelMembers,
  sourceChannelIdentityAliases,
  scheduledJobConfigs,
  configBackups,
  channelFailoverPolicies,
  contentManifest,
  // 009-m3u-control-plane
  mergeCandidates,
  streamHealthObservations,
  failoverEvents,
  outputGrants,
  outputPublications,
} from "@magi/backend-core";
