/**
 * Output grant use cases (009-m3u-control-plane T047).
 *
 * Three operator-facing actions on per-player / per-device output grants:
 *   - CreateOutputGrantUseCase: mint a new grant + return plaintext once
 *   - RotateOutputGrantUseCase: rotate an existing grant's secret
 *   - RevokeOutputGrantUseCase: revoke (optional reason)
 *
 * Plaintext tokens are generated by the injected `OutputGrantCrypto` port.
 * The use cases NEVER log or persist the plaintext — only the prefix (4-char
 * hint for support) + the SHA-256 hash. The plaintext is returned in the
 * response DTO exactly once on create/rotate; subsequent reads only see the
 * summary VO.
 */
import { Inject, Injectable } from "@nestjs/common";
import { randomBytes, createHash, timingSafeEqual } from "node:crypto";
import type {
  IOutputGrantRepository,
} from "@/domain/output-composition";
import type {
  OutputGrantIssuedVo,
  OutputGrantSummaryVo,
  OutputGrantProfile,
} from "@magi/types";

/** Token issuer: generates plaintext + prefix + hash. Pure, no I/O. */
export interface OutputGrantCrypto {
  /** Returns a fresh plaintext secret + its prefix + its hash. */
  generate(): { plaintext: string; prefix: string; hash: string };
  /** Hash an existing plaintext (used by the playlist guard for lookup). */
  hash(plaintext: string): string;
}

/** Default crypto: 32-byte URL-safe base64 token + 12-char prefix + sha256 hash. */
export const GRANT_TOKEN_PREFIX = "mg_pl_";

@Injectable()
export class NodeOutputGrantCrypto implements OutputGrantCrypto {
  generate(): { plaintext: string; prefix: string; hash: string } {
    const bytes = randomBytes(32);
    const plaintext = GRANT_TOKEN_PREFIX + bytes.toString("base64url");
    // Prefix is the first 12 chars after the namespace — long enough to be
    // recognizable in logs, short enough not to leak the secret.
    const prefix = plaintext.slice(0, GRANT_TOKEN_PREFIX.length + 8);
    return { plaintext, prefix, hash: this.hash(plaintext) };
  }

  hash(plaintext: string): string {
    return "sha256:" + createHash("sha256").update(plaintext).digest("hex");
  }

  /**
   * Constant-time equality for grant lookups. The playlist guard hashes the
   * incoming grant first, then compares the resulting hash against stored
   * hashes; this helper keeps the comparison itself non-leaky as a defense
   * in depth.
   */
  safeEqualHashes(a: string, b: string): boolean {
    if (a.length !== b.length) return false;
    try {
      return timingSafeEqual(Buffer.from(a), Buffer.from(b));
    } catch {
      return false;
    }
  }
}

export interface CreateOutputGrantInput {
  readonly ownerUserId: string;
  readonly displayName: string;
  readonly deviceClientId: string | null;
  readonly profile: OutputGrantProfile;
  readonly expiresAt: Date | null;
  readonly playlistBaseUrl: string;
}

@Injectable()
export class CreateOutputGrantUseCase {
  constructor(
    @Inject("OUTPUT_GRANT_REPOSITORY")
    private readonly repo: IOutputGrantRepository,
    @Inject("OUTPUT_GRANT_CRYPTO")
    private readonly crypto: OutputGrantCrypto,
  ) {}

  async execute(input: CreateOutputGrantInput): Promise<OutputGrantIssuedVo> {
    const generated = this.crypto.generate();
    const grant = await this.repo.create({
      ownerUserId: input.ownerUserId,
      displayName: input.displayName,
      deviceClientId: input.deviceClientId,
      profile: input.profile,
      tokenPrefix: generated.prefix,
      tokenHash: generated.hash,
      expiresAt: input.expiresAt,
    });
    return {
      grant,
      playlistUrl: buildPlaylistUrl(input.playlistBaseUrl, generated.plaintext),
    };
  }
}

export interface RotateOutputGrantInput {
  readonly id: string;
  readonly playlistBaseUrl: string;
  readonly reason?: string;
}

@Injectable()
export class RotateOutputGrantUseCase {
  constructor(
    @Inject("OUTPUT_GRANT_REPOSITORY")
    private readonly repo: IOutputGrantRepository,
    @Inject("OUTPUT_GRANT_CRYPTO")
    private readonly crypto: OutputGrantCrypto,
  ) {}

  async execute(input: RotateOutputGrantInput): Promise<OutputGrantIssuedVo> {
    const generated = this.crypto.generate();
    const grant = await this.repo.rotate(input.id, {
      tokenPrefix: generated.prefix,
      tokenHash: generated.hash,
    });
    if (!grant) {
      throw new OutputGrantNotFoundError(input.id);
    }
    void input.reason;
    return {
      grant,
      playlistUrl: buildPlaylistUrl(input.playlistBaseUrl, generated.plaintext),
    };
  }
}

export interface RevokeOutputGrantInput {
  readonly id: string;
  readonly reason: string | null;
}

@Injectable()
export class RevokeOutputGrantUseCase {
  constructor(
    @Inject("OUTPUT_GRANT_REPOSITORY")
    private readonly repo: IOutputGrantRepository,
  ) {}

  async execute(input: RevokeOutputGrantInput): Promise<OutputGrantSummaryVo> {
    const grant = await this.repo.revoke(input.id, input.reason);
    if (!grant) {
      throw new OutputGrantNotFoundError(input.id);
    }
    return grant;
  }
}

export class OutputGrantNotFoundError extends Error {
  constructor(public readonly grantId: string) {
    super(`Output grant not found: ${grantId}`);
    this.name = "OutputGrantNotFoundError";
  }
}

/**
 * Build the player-facing playlist URL with the grant token in the query
 * string. The token is opaque to playlist clients; the guard reads it via
 * `req.query.grant`.
 */
export function buildPlaylistUrl(baseUrl: string, plaintext: string): string {
  const separator = baseUrl.includes("?") ? "&" : "?";
  return `${baseUrl}${separator}grant=${encodeURIComponent(plaintext)}`;
}
