/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardProgrammesRouteImport } from './routes/dashboard/programmes'
import { Route as DashboardEpgMatchingRouteImport } from './routes/dashboard/epg-matching'
import { Route as DashboardEpgRouteImport } from './routes/dashboard/epg'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard/channels'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgrammesRoute = DashboardProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEpgMatchingRoute = DashboardEpgMatchingRouteImport.update({
  id: '/epg-matching',
  path: '/epg-matching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEpgRoute = DashboardEpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/epg': typeof DashboardEpgRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/programmes': typeof DashboardProgrammesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/epg': typeof DashboardEpgRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/programmes': typeof DashboardProgrammesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/epg': typeof DashboardEpgRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/programmes': typeof DashboardProgrammesRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/channels'
    | '/dashboard/epg'
    | '/dashboard/epg-matching'
    | '/dashboard/programmes'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/channels'
    | '/dashboard/epg'
    | '/dashboard/epg-matching'
    | '/dashboard/programmes'
    | '/dashboard/tasks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/channels'
    | '/dashboard/epg'
    | '/dashboard/epg-matching'
    | '/dashboard/programmes'
    | '/dashboard/tasks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/programmes': {
      id: '/dashboard/programmes'
      path: '/programmes'
      fullPath: '/dashboard/programmes'
      preLoaderRoute: typeof DashboardProgrammesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/epg-matching': {
      id: '/dashboard/epg-matching'
      path: '/epg-matching'
      fullPath: '/dashboard/epg-matching'
      preLoaderRoute: typeof DashboardEpgMatchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/epg': {
      id: '/dashboard/epg'
      path: '/epg'
      fullPath: '/dashboard/epg'
      preLoaderRoute: typeof DashboardEpgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/channels': {
      id: '/dashboard/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardEpgRoute: typeof DashboardEpgRoute
  DashboardEpgMatchingRoute: typeof DashboardEpgMatchingRoute
  DashboardProgrammesRoute: typeof DashboardProgrammesRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardEpgRoute: DashboardEpgRoute,
  DashboardEpgMatchingRoute: DashboardEpgMatchingRoute,
  DashboardProgrammesRoute: DashboardProgrammesRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
