/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOutputGuideRouteImport } from './routes/dashboard/output-guide'
import { Route as DashboardOutputAddressesRouteImport } from './routes/dashboard/output-addresses'
import { Route as DashboardEpgMatchingRouteImport } from './routes/dashboard/epg-matching'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardChannelsIndexRouteImport } from './routes/dashboard/channels/index'
import { Route as DashboardBackupsIndexRouteImport } from './routes/dashboard/backups/index'
import { Route as DashboardAuditIndexRouteImport } from './routes/dashboard/audit/index'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks/$taskId'
import { Route as DashboardSourcesXmltvRouteImport } from './routes/dashboard/sources/xmltv'
import { Route as DashboardSourcesProgrammesRouteImport } from './routes/dashboard/sources/programmes'
import { Route as DashboardSourcesM3uRouteImport } from './routes/dashboard/sources/m3u'
import { Route as DashboardSourcesChannelsRouteImport } from './routes/dashboard/sources/channels'
import { Route as DashboardChannelsChannelIdRouteImport } from './routes/dashboard/channels/$channelId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutputGuideRoute = DashboardOutputGuideRouteImport.update({
  id: '/output-guide',
  path: '/output-guide',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutputAddressesRoute =
  DashboardOutputAddressesRouteImport.update({
    id: '/output-addresses',
    path: '/output-addresses',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEpgMatchingRoute = DashboardEpgMatchingRouteImport.update({
  id: '/epg-matching',
  path: '/epg-matching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelsIndexRoute = DashboardChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsIndexRoute = DashboardBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditIndexRoute = DashboardAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesXmltvRoute = DashboardSourcesXmltvRouteImport.update({
  id: '/sources/xmltv',
  path: '/sources/xmltv',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesProgrammesRoute =
  DashboardSourcesProgrammesRouteImport.update({
    id: '/sources/programmes',
    path: '/sources/programmes',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSourcesM3uRoute = DashboardSourcesM3uRouteImport.update({
  id: '/sources/m3u',
  path: '/sources/m3u',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesChannelsRoute =
  DashboardSourcesChannelsRouteImport.update({
    id: '/sources/channels',
    path: '/sources/channels',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChannelsChannelIdRoute =
  DashboardChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/output-addresses': typeof DashboardOutputAddressesRoute
  '/dashboard/output-guide': typeof DashboardOutputGuideRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/sources/channels': typeof DashboardSourcesChannelsRoute
  '/dashboard/sources/m3u': typeof DashboardSourcesM3uRoute
  '/dashboard/sources/programmes': typeof DashboardSourcesProgrammesRoute
  '/dashboard/sources/xmltv': typeof DashboardSourcesXmltvRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/backups/': typeof DashboardBackupsIndexRoute
  '/dashboard/channels/': typeof DashboardChannelsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/output-addresses': typeof DashboardOutputAddressesRoute
  '/dashboard/output-guide': typeof DashboardOutputGuideRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/sources/channels': typeof DashboardSourcesChannelsRoute
  '/dashboard/sources/m3u': typeof DashboardSourcesM3uRoute
  '/dashboard/sources/programmes': typeof DashboardSourcesProgrammesRoute
  '/dashboard/sources/xmltv': typeof DashboardSourcesXmltvRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/audit': typeof DashboardAuditIndexRoute
  '/dashboard/backups': typeof DashboardBackupsIndexRoute
  '/dashboard/channels': typeof DashboardChannelsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/epg-matching': typeof DashboardEpgMatchingRoute
  '/dashboard/output-addresses': typeof DashboardOutputAddressesRoute
  '/dashboard/output-guide': typeof DashboardOutputGuideRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/channels/$channelId': typeof DashboardChannelsChannelIdRoute
  '/dashboard/sources/channels': typeof DashboardSourcesChannelsRoute
  '/dashboard/sources/m3u': typeof DashboardSourcesM3uRoute
  '/dashboard/sources/programmes': typeof DashboardSourcesProgrammesRoute
  '/dashboard/sources/xmltv': typeof DashboardSourcesXmltvRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/audit/': typeof DashboardAuditIndexRoute
  '/dashboard/backups/': typeof DashboardBackupsIndexRoute
  '/dashboard/channels/': typeof DashboardChannelsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/epg-matching'
    | '/dashboard/output-addresses'
    | '/dashboard/output-guide'
    | '/dashboard/'
    | '/dashboard/channels/$channelId'
    | '/dashboard/sources/channels'
    | '/dashboard/sources/m3u'
    | '/dashboard/sources/programmes'
    | '/dashboard/sources/xmltv'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/audit/'
    | '/dashboard/backups/'
    | '/dashboard/channels/'
    | '/dashboard/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/epg-matching'
    | '/dashboard/output-addresses'
    | '/dashboard/output-guide'
    | '/dashboard'
    | '/dashboard/channels/$channelId'
    | '/dashboard/sources/channels'
    | '/dashboard/sources/m3u'
    | '/dashboard/sources/programmes'
    | '/dashboard/sources/xmltv'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/audit'
    | '/dashboard/backups'
    | '/dashboard/channels'
    | '/dashboard/tasks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/epg-matching'
    | '/dashboard/output-addresses'
    | '/dashboard/output-guide'
    | '/dashboard/'
    | '/dashboard/channels/$channelId'
    | '/dashboard/sources/channels'
    | '/dashboard/sources/m3u'
    | '/dashboard/sources/programmes'
    | '/dashboard/sources/xmltv'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/audit/'
    | '/dashboard/backups/'
    | '/dashboard/channels/'
    | '/dashboard/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/output-guide': {
      id: '/dashboard/output-guide'
      path: '/output-guide'
      fullPath: '/dashboard/output-guide'
      preLoaderRoute: typeof DashboardOutputGuideRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/output-addresses': {
      id: '/dashboard/output-addresses'
      path: '/output-addresses'
      fullPath: '/dashboard/output-addresses'
      preLoaderRoute: typeof DashboardOutputAddressesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/epg-matching': {
      id: '/dashboard/epg-matching'
      path: '/epg-matching'
      fullPath: '/dashboard/epg-matching'
      preLoaderRoute: typeof DashboardEpgMatchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/channels/': {
      id: '/dashboard/channels/'
      path: '/channels'
      fullPath: '/dashboard/channels/'
      preLoaderRoute: typeof DashboardChannelsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backups/': {
      id: '/dashboard/backups/'
      path: '/backups'
      fullPath: '/dashboard/backups/'
      preLoaderRoute: typeof DashboardBackupsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit/': {
      id: '/dashboard/audit/'
      path: '/audit'
      fullPath: '/dashboard/audit/'
      preLoaderRoute: typeof DashboardAuditIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources/xmltv': {
      id: '/dashboard/sources/xmltv'
      path: '/sources/xmltv'
      fullPath: '/dashboard/sources/xmltv'
      preLoaderRoute: typeof DashboardSourcesXmltvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources/programmes': {
      id: '/dashboard/sources/programmes'
      path: '/sources/programmes'
      fullPath: '/dashboard/sources/programmes'
      preLoaderRoute: typeof DashboardSourcesProgrammesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources/m3u': {
      id: '/dashboard/sources/m3u'
      path: '/sources/m3u'
      fullPath: '/dashboard/sources/m3u'
      preLoaderRoute: typeof DashboardSourcesM3uRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources/channels': {
      id: '/dashboard/sources/channels'
      path: '/sources/channels'
      fullPath: '/dashboard/sources/channels'
      preLoaderRoute: typeof DashboardSourcesChannelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/channels/$channelId': {
      id: '/dashboard/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/dashboard/channels/$channelId'
      preLoaderRoute: typeof DashboardChannelsChannelIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEpgMatchingRoute: typeof DashboardEpgMatchingRoute
  DashboardOutputAddressesRoute: typeof DashboardOutputAddressesRoute
  DashboardOutputGuideRoute: typeof DashboardOutputGuideRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChannelsChannelIdRoute: typeof DashboardChannelsChannelIdRoute
  DashboardSourcesChannelsRoute: typeof DashboardSourcesChannelsRoute
  DashboardSourcesM3uRoute: typeof DashboardSourcesM3uRoute
  DashboardSourcesProgrammesRoute: typeof DashboardSourcesProgrammesRoute
  DashboardSourcesXmltvRoute: typeof DashboardSourcesXmltvRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardAuditIndexRoute: typeof DashboardAuditIndexRoute
  DashboardBackupsIndexRoute: typeof DashboardBackupsIndexRoute
  DashboardChannelsIndexRoute: typeof DashboardChannelsIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEpgMatchingRoute: DashboardEpgMatchingRoute,
  DashboardOutputAddressesRoute: DashboardOutputAddressesRoute,
  DashboardOutputGuideRoute: DashboardOutputGuideRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChannelsChannelIdRoute: DashboardChannelsChannelIdRoute,
  DashboardSourcesChannelsRoute: DashboardSourcesChannelsRoute,
  DashboardSourcesM3uRoute: DashboardSourcesM3uRoute,
  DashboardSourcesProgrammesRoute: DashboardSourcesProgrammesRoute,
  DashboardSourcesXmltvRoute: DashboardSourcesXmltvRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardAuditIndexRoute: DashboardAuditIndexRoute,
  DashboardBackupsIndexRoute: DashboardBackupsIndexRoute,
  DashboardChannelsIndexRoute: DashboardChannelsIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
